---
name: tests
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  unit-tests:
    strategy:
      matrix:
        go-version: [1.19, 1.20.x, 1.21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
