# Repository labels (managed via workflow)
# Sync with: .github/workflows/labels-sync.yml

- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: chore
  color: c5def5
  description: Maintenance, refactor, or non-feature changes

- name: automation
  color: bfd4f2
  description: CI/CD or automation related changes

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

