# docker-compose.yml - Complete secure notes app with automatic setup

services:
  # PostgreSQL with automatic SSL setup
  postgres:
    image: postgres:15-alpine
    container_name: leaflock-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeThisSecurePassword123!}
      POSTGRES_DB: notes
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    command: ["postgres"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leaflock-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 20
    restart: unless-stopped

  # Redis for session management
  redis:
    image: redis:7-alpine
    container_name: leaflock-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-ChangeThisRedisPassword123!}
    volumes:
      - redis_data:/data
    networks:
      - leaflock-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" --no-auth-warning PING | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leaflock-backend
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-ChangeThisSecurePassword123!}@postgres:5432/notes?sslmode=prefer
      REDIS_URL: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:-ChangeThisRedisPassword123!}
      JWT_SECRET: ${JWT_SECRET:-ChangeThisToRandom64CharStringForProductionUsePlease!}
      SERVER_ENCRYPTION_KEY: ${SERVER_ENCRYPTION_KEY:-ChangeThisToRandom32CharString!}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost,https://localhost}
      ADMIN_USER_IDS: ${ADMIN_USER_IDS:-}
      ADMIN_USER_IDS_FILE: /run/config/notes.env
      APP_ENV: ${APP_ENV:-development}
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/run/config/notes.env:ro
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - leaflock-network
    healthcheck:
      disable: true
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8080}
        VITE_ENABLE_ADMIN_PANEL: ${VITE_ENABLE_ADMIN_PANEL:-false}
    container_name: leaflock-frontend
    environment:
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL:-http://backend:8080}
      PORT: ${FRONTEND_CONTAINER_PORT:-80}
    ports:
      - "3000:${FRONTEND_CONTAINER_PORT:-80}"
    depends_on:
      - backend
    networks:
      - leaflock-network
    healthcheck:
      test: ["CMD-SHELL", "pidof nginx > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Nginx reverse proxy (optional - for production-like setup)
  nginx:
    image: nginx:alpine
    container_name: leaflock-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - leaflock-network
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  leaflock-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

# === .env.example - Environment variables template ===
# Copy this to .env and update with secure values
#
# POSTGRES_PASSWORD=GenerateSecurePasswordHere123!
# REDIS_PASSWORD=GenerateSecureRedisPasswordHere123!
# JWT_SECRET=GenerateRandom64CharacterStringHereForJWTSigning!
# SERVER_ENCRYPTION_KEY=GenerateRandom32CharStringHere!
# CORS_ORIGINS=http://localhost:3000,http://localhost
# VITE_API_URL=http://localhost:8080
