# docker-compose.coolify.yml - LeafLock deployment for Coolify
# Optimized for Coolify's deployment model with automatic service discovery
# 
# COOLIFY DEPLOYMENT NOTES:
# 1. Frontend uses traefik.enable=true for external access via HTTPS
# 2. Backend is internal-only, accessed via nginx proxy from frontend  
# 3. External Traefik network (`coolify-infra`) is required for public routing
# 4. No port mappings - Coolify handles external routing automatically
# 5. Environment variables set in Coolify UI override defaults
#
# REQUIRED ENVIRONMENT VARIABLES IN COOLIFY:
# - POSTGRES_PASSWORD (secure random string)
# - REDIS_PASSWORD (secure random string) 
# - JWT_SECRET (64+ character string)
# - SERVER_ENCRYPTION_KEY (32 character string)
# - CORS_ORIGINS (your domain, e.g., https://your-app.coolify.io)
#
# DEPLOYMENT TIPS:
# - Enable "Preserve Repository During Deployment" if build fails
# - Check that docker-compose.coolify.yml is properly recognized
#
# NOTE: Docker security warnings about build arguments are expected and harmless.

# version: '3.8' - Removed to avoid obsolete attribute warning

services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in Coolify environment variables}
      POSTGRES_DB: leaflock
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      # Keep PGDATA at the volume root so existing data from earlier versions mounts cleanly
      PGDATA: /var/lib/postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal
    # Aggressive health checks for fast startup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 3s
      timeout: 2s
      start_period: 10s
      retries: 5
    # Resource limits to prevent contention
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    restart: unless-stopped

  # Redis Cache for Sessions  
  redis:
    image: redis:8-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:?Please set REDIS_PASSWORD in Coolify environment variables}"]
    volumes:
      - redis_data:/data
    networks:
      - internal
    # Fast Redis health checks
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:?Please set REDIS_PASSWORD in Coolify environment variables}", "--no-auth-warning", "PING"]
      interval: 2s
      timeout: 1s
      start_period: 5s
      retries: 3
    # Resource limits for Redis
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 64M
          cpus: '0.1'
    restart: unless-stopped

  # Go Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # Database Configuration
      # IMPORTANT: sslmode=disable required for containerized PostgreSQL without TLS setup
      # DO NOT change to sslmode=prefer/require unless PostgreSQL container has proper TLS certificates
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:?}@postgres:5432/leaflock?sslmode=disable&connect_timeout=10
      
      # Redis Configuration
      REDIS_URL: redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:?}
      
      # Security Keys (CRITICAL: Must be set in Coolify UI)
      JWT_SECRET: ${JWT_SECRET:?Please set JWT_SECRET (64 chars) in Coolify environment variables}
      SERVER_ENCRYPTION_KEY: ${SERVER_ENCRYPTION_KEY:?Please set SERVER_ENCRYPTION_KEY (32 chars) in Coolify environment variables}
      
      # CORS and API Configuration - Updated for Coolify deployment
      # Include your actual domain in production, e.g. https://your-app.coolify.io
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      PORT: 8080
      
      # Application Settings
      APP_ENV: ${APP_ENV:-production}
      ENABLE_REGISTRATION: ${ENABLE_REGISTRATION:-true}

      # Default Admin User Configuration
      ENABLE_DEFAULT_ADMIN: ${ENABLE_DEFAULT_ADMIN:-true}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL:-admin@leaflock.app}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:-AdminPass123!}

      # Admin Configuration (Optional)
      ADMIN_USER_IDS: ${ADMIN_USER_IDS:-}

      # Progressive Rate Limiting Configuration
      RATE_LIMIT_MODE: ${RATE_LIMIT_MODE:-progressive}
      IP_RATE_LIMIT_ENABLED: ${IP_RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_DECAY_MINUTES: ${RATE_LIMIT_DECAY_MINUTES:-5}
      RATE_LIMIT_USE_SUBNET: ${RATE_LIMIT_USE_SUBNET:-false}
      MAX_DELAY_SECONDS: ${MAX_DELAY_SECONDS:-60}
      TRUSTED_IP_RANGES: ${TRUSTED_IP_RANGES:-}

      # Monitoring
      ENABLE_METRICS: ${ENABLE_METRICS:-true}
    # Optimal service dependency order
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    # Health check for container orchestration - extended timeouts for async initialization
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --timeout=10 http://localhost:8080/api/v1/health/live || exit 1"]
      interval: 15s
      timeout: 10s
      start_period: 60s
      retries: 5
    # Resource limits for backend
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped
    networks:
      - internal
    # Backend is internal-only, no special labels needed
    # Coolify will automatically add coolify.managed=true

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build-time environment variables for frontend API connection
        # Use relative API calls that work with Coolify's proxy
        VITE_API_URL: ${VITE_API_URL:-}
        VITE_ENABLE_ADMIN_PANEL: ${VITE_ENABLE_ADMIN_PANEL:-false}
    environment:
      # Runtime environment variables for frontend
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL:-http://backend:8080}
      # Use standard HTTP port - Coolify handles external routing
      PORT: 80
    depends_on:
      backend:
        condition: service_healthy
    # Optimized nginx health checks for Coolify
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --timeout=2 http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3
    # Resource limits for frontend nginx
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 32M
          cpus: '0.05'
    restart: unless-stopped
    networks:
      - internal
      - coolify-infra
    labels:
      # Enable Traefik proxy for external access - Coolify will auto-configure
      - "traefik.enable=true"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  internal:
    driver: bridge
  coolify-infra:
    external: true
    name: coolify-infra

# Legacy network example retained for reference only
# networks:
#   leaflock-network:
#     driver: bridge

# Coolify Fast Startup Optimization:
# PERFORMANCE OPTIMIZATIONS IMPLEMENTED:
# 1. Aggressive Health Checks:
#    - PostgreSQL: 3s intervals, 10s start period, 2s timeout
#    - Redis: 2s intervals, 5s start period, 1s timeout  
#    - Backend: 5s intervals, 15s start period, 3s timeout
#    - Frontend: 3s intervals, 10s start period, 2s timeout
#
# 2. Progressive Dependencies:
#    - Redis starts first (fastest)
#    - PostgreSQL starts in parallel
#    - Backend waits for both DB services to be healthy
#    - Frontend waits for backend to be healthy
#
# 3. Resource Limits (prevents resource contention):
#    - PostgreSQL: 512M/256M memory, 0.5/0.2 CPU
#    - Redis: 256M/64M memory, 0.3/0.1 CPU
#    - Backend: 1G/512M memory, 1.0/0.5 CPU
#    - Frontend: 128M/32M memory, 0.2/0.05 CPU
#
# 4. Optimized Health Check Commands:
#    - Backend: Uses /api/v1/health endpoint for comprehensive checks
#    - Frontend: Uses wget with timeout for nginx health
#    - Redis: Direct PING command with auth
#    - PostgreSQL: pg_isready for fast connection test
#
# TARGET STARTUP TIME: Under 30 seconds
# 
# DEPLOYMENT NOTES:
# 1. Set all required environment variables in Coolify UI
# 2. Use strong, randomly generated passwords and keys
# 3. Configure domain and SSL in Coolify for the frontend service
# 4. Monitor logs during deployment: docker compose logs -f
# 5. Health endpoints:
#    - Backend: http://your-backend:8080/api/v1/health
#    - Frontend: http://your-frontend/
#
# Rate Limiting Configuration:
# - To DISABLE rate limiting entirely: Set RATE_LIMIT_MODE=disabled
# - For progressive delays (default): Set RATE_LIMIT_MODE=progressive
# - For shared IP environments: Set RATE_LIMIT_USE_SUBNET=true
# - To disable IP rate limiting: Set IP_RATE_LIMIT_ENABLED=false
