apiVersion: v1
kind: Pod
metadata:
  name: leaflock
  labels:
    app: leaflock
spec:
  containers:
  - name: postgres
    # Use fully qualified image reference to avoid unqualified registry resolution issues
    image: docker.io/library/postgres:18-alpine@sha256:70b32afe0c274b4d93098fd724fcdaab3aba47270a4f1e63cbf9cc69d7bf1be4
    env:
    - name: POSTGRES_PASSWORD
      value: "ChangeThisSecurePassword123!"
    - name: POSTGRES_DB
      value: "notes"
    - name: POSTGRES_USER
      value: "postgres"
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
      
  - name: redis
    # Use fully qualified image reference; keep tag-only for compatibility
    image: docker.io/library/redis:8-alpine@sha256:987c376c727652f99625c7d205a1cba3cb2c53b92b0b62aade2bd48ee1593232
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "ChangeThisRedisPassword123!"]
    ports:
    - containerPort: 6379
      hostPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data

  volumes:
  - name: postgres-data
    emptyDir: {}
  - name: redis-data
    emptyDir: {}
