apiVersion: v1
kind: Pod
metadata:
  name: leaflock
  labels:
    app: leaflock
spec:
  containers:
  - name: postgres
    # Use fully qualified image reference to avoid unqualified registry resolution issues
    image: docker.io/library/postgres:18-alpine@sha256:9636ae7feacd8d630303eede7f95cd0f472d514e7864422c6aa8ea07b2171df8
    env:
    - name: POSTGRES_PASSWORD
      value: "ChangeThisSecurePassword123!"
    - name: POSTGRES_DB
      value: "notes"
    - name: POSTGRES_USER
      value: "postgres"
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
      
  - name: redis
    # Use fully qualified image reference; keep tag-only for compatibility
    image: docker.io/library/redis:8-alpine@sha256:1c78f5e7512cc8b22b0edc95c20e7abd9e1fd832e5dfd5c3c6b59ce82fb238d0
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "ChangeThisRedisPassword123!"]
    ports:
    - containerPort: 6379
      hostPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data

  volumes:
  - name: postgres-data
    emptyDir: {}
  - name: redis-data
    emptyDir: {}
