apiVersion: v1
kind: Pod
metadata:
  name: secure-notes
  labels:
    app: secure-notes
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: "ChangeThisSecurePassword123!"
    - name: POSTGRES_DB
      value: "notes"
    - name: POSTGRES_USER
      value: "postgres"
    ports:
    - containerPort: 5432
      hostPort: 5432
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
      
  - name: redis
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "ChangeThisRedisPassword123!"]
    ports:
    - containerPort: 6379
      hostPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data

  volumes:
  - name: postgres-data
    emptyDir: {}
  - name: redis-data
    emptyDir: {}