# GolangCI-Lint configuration for Secure Notes backend
# Minimal v2 config for golangci-lint 2.5.0 / MegaLinter v9 compatibility

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: error
