# GolangCI-Lint configuration for Secure Notes backend
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      ignore: fmt:.*,io/ioutil:^Read.*
  exclusions:
    generated: lax
    rules:
      - path: '_test\.go$'
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

severity:
  default: error
