FROM docker.io/golang:1.25-alpine AS builder

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

RUN apk --no-cache add build-base git ca-certificates tzdata \
    && addgroup -g 10001 appuser \
    && adduser -D -u 10001 -G appuser appuser

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build \
      -ldflags='-w -s -extldflags "-static"' \
      -trimpath \
      -o leaflock-backend . && \
    chmod +x /build/leaflock-backend

RUN go build \
      -ldflags='-w -s -extldflags "-static"' \
      -trimpath \
      -o entrypoint ./cmd/entrypoint && \
    chmod +x /build/entrypoint

FROM scratch

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder --chmod=0755 /build/leaflock-backend /app/leaflock-backend
COPY --from=builder --chmod=0755 /build/entrypoint /app/entrypoint

USER appuser:appuser

EXPOSE 8080

ENV BACKEND_BINARY=/app/leaflock-backend

ENTRYPOINT ["/app/entrypoint"]
