blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/RelativeSure/notes/discussions
    about: Ask questions, brainstorm ideas, and discuss improvements.
