name: Documentation Tests

on:
  push:
    branches: [master, examples]
  pull_request:
    branches: [master, examples]

permissions:
  contents: read

jobs:
  doctests:
    name: doctests
    runs-on: ubuntu-latest

    services:
      redis-stack:
        image: redislabs/client-libs-test:8.2.1@sha256:c9e3e99f039b04c9ba22586284d16f730d0eb606727f4ba867a93b084eb0f3e8
        env:
          TLS_ENABLED: no
          REDIS_CLUSTER: no
          PORT: 6379
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.24"]

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test doc examples
        working-directory: ./doctests
        run: make test
