{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secure-notes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "secure-notes.fullname" . }}-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "secure-notes.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "secure-notes.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "secure-notes.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}