{{- if or .Values.secrets.jwtSecret .Values.secrets.serverEncryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-notes.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ "please-change-this-jwt-secret-in-production-for-security" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.serverEncryptionKey }}
  server-encryption-key: {{ .Values.secrets.serverEncryptionKey | b64enc | quote }}
  {{- else }}
  server-encryption-key: {{ "change-this-32-char-key-in-prod" | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if .Values.postgresql.enabled }}
{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-notes.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | default "postgres-change-me" | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | default "notes-change-me" | b64enc | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.redis.enabled }}
{{- if not .Values.redis.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secure-notes.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "secure-notes.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
  annotations:
    {{- include "secure-notes.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | default "redis-change-me" | b64enc | quote }}
{{- end }}
{{- end }}