name: validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: read

jobs:
  linters:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: prepare generated code
        run: make prepare
      - name: lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --print-resources-usage --timeout=10m --verbose
