redis:
  master:
    configuration: |
      # Network and connection
      bind 0.0.0.0
      port 6379

      # Persistence
      appendonly yes
      appendfsync everysec

      # Memory management
      maxmemory-policy allkeys-lru

      # Logging
      loglevel notice
    disableCommands: []  # Remove the disable commands that are causing issues

  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""

postgresql:
  metrics:
    enabled: false  # Disable metrics to avoid crash issues
  primary:
    # Fix the shared_preload_libraries conflict
    extendedConfiguration: |
      # Connection settings
      max_connections = 100
      shared_buffers = 256MB
      effective_cache_size = 1GB
      work_mem = 4MB
      maintenance_work_mem = 64MB
      
      # SSL settings (disabled for k3s development)
      ssl = off
      
      # Logging
      log_statement = 'all'
      log_duration = on
      log_connections = on
      log_disconnections = on
      
      # Extensions - only use pgaudit for now
      # shared_preload_libraries is set by environment variable
    
    # Simplified init scripts to avoid extension conflicts
    initdb:
      scripts:
        01-basic-setup.sql: |
          -- Basic database setup
          CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

# Temporarily disable network policies for debugging
networkPolicy:
  enabled: false