name: Auto labeler

on:
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened]
permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: labeler
        uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
