name: "Sync docs"

on:
  push:
    branches:
      - v2
    paths:
      - "docs/**"
  release:
    types: [published]

jobs:
  sync-docs:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "22"

      - name: Sync docs
        run: ./.github/scripts/sync_docs.sh
        env:
          EVENT: ${{ github.event_name }}
          TAG_NAME: ${{ github.ref_name }}
          TOKEN: ${{ secrets.DOC_SYNC_TOKEN }}
