baseURL = "https://docs.leaflock.app/"
languageCode = "en"
title = "LeafLock Documentation"
pluralizeListTitles = false

enableGitInfo = true
enableRobotsTXT = true

timeZone = "UTC"

[pagination]
  pagerSize = 20

[params]
  contactEmail = "contact@leaflock.app"
  description = "Secure, end-to-end encrypted notes with zero-knowledge architecture"
  author = "LeafLock Team"
  keywords = ["leaflock", "encryption", "privacy", "end-to-end", "zero-knowledge", "secure notes"]
  version = "1.0.0"

  [params.social]
    github = "https://github.com/RelativeSure/LeafLock"
    email = "contact@leaflock.app"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 2

[module]
  [[module.mounts]]
    source = "../"
    target = "content/pages"
    includeFiles = ["**.md"]
    excludeFiles = ["site/**"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Documentation"
    url = "/pages/"
    weight = 20
    identifier = "documentation"
  [[menu.main]]
    name = "Legal"
    url = "/categories/legal/"
    weight = 30
    identifier = "legal"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/RelativeSure/LeafLock"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML", "RSS"]
