{{- if and .Values.monitoring.enabled .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "leaflock.fullname" . }}
  namespace: {{ .Values.monitoring.prometheusRule.namespace | default .Release.Namespace }}
  labels:
    {{- include "leaflock.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: leaflock.rules
    rules:
    {{- range .Values.monitoring.prometheusRule.rules }}
    - alert: {{ .alert }}
      expr: {{ .expr }}
      {{- if .for }}
      for: {{ .for }}
      {{- end }}
      {{- if .labels }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      {{- end }}
      {{- if .annotations }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.monitoring.prometheusRule.additionalRules }}
    {{- toYaml .Values.monitoring.prometheusRule.additionalRules | nindent 4 }}
    {{- end }}
{{- end }}