name: CI

on:
  push:
    branches: [ master, v1 ]
  pull_request:
    branches: [ master, v1 ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        go-version: ["1.19", "1.20"]

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Test
      run: go test -v -race ./...
