name: Claude Code (on mention - extended)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, assigned]
  workflow_dispatch:

jobs:
  claude:
    # Triggers (case-insensitive @claude):
    # - Issue or PR comment
    # - Inline PR review comment
    # - Full PR review body (on submission)
    # - Issue opened (title or body)
    # - Issue assigned (body)
    # - Manual dispatch
    if: >
      (
        github.event_name == 'issue_comment' &&
        github.event.comment.body != null &&
        contains(toLower(github.event.comment.body), '@claude')
      ) ||
      (
        github.event_name == 'pull_request_review_comment' &&
        github.event.comment.body != null &&
        contains(toLower(github.event.comment.body), '@claude')
      ) ||
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.body != null &&
        contains(toLower(github.event.review.body), '@claude')
      ) ||
      (
        github.event_name == 'issues' &&
        (
          (
            github.event.action == 'opened' &&
            (
              (github.event.issue.body != null && contains(toLower(github.event.issue.body), '@claude')) ||
              contains(toLower(github.event.issue.title), '@claude')
            )
          ) ||
          (
            github.event.action == 'assigned' &&
            github.event.issue.body != null &&
            contains(toLower(github.event.issue.body), '@claude')
          )
        )
      ) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      actions: read  # Enables reading CI results if the action leverages them

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read

          # Optional overrides:
          # trigger_phrase: "/claude"       # Alternative single trigger phrase (action built-in)
          # model: "claude-opus-4-1-20250805"
          # allowed_tools: "Bash(npm install),Bash(npm run build),Bash(npm run test:unit)"
          # custom_instructions: |
          #   Follow repository coding standards.
          #   Ensure new or changed logic includes tests.
          # claude_env: |
          #   NODE_ENV: test
