name: Claude Code Review (on mention - extended)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  claude-review:
    # Conditions:
    # - Regular issue/PR comment containing @claude (on a PR)
    # - Inline PR review comment containing @claude
    # - Submitted PR review body containing @claude
    # - Manual dispatch
    if: >
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.body != null &&
        contains(toLower(github.event.comment.body), '@claude')
      ) ||
      (
        github.event_name == 'pull_request_review_comment' &&
        github.event.comment.body != null &&
        contains(toLower(github.event.comment.body), '@claude')
      ) ||
      (
        github.event_name == 'pull_request_review' &&
        github.event.review.body != null &&
        contains(toLower(github.event.review.body), '@claude')
      ) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # write so the action can post reviews/comments
      issues: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Main review prompt
          direct_prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Be constructive and helpful in your feedback.

          # Optional Enhancements (uncomment as needed):
          # use_sticky_comment: true
          # model: "claude-opus-4-1-20250805"
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
          # context_note: "Triggered by: ${{ github.event_name }} event"
