name: Build Docs Site

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs-site.yml'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs-site.yml'
  workflow_dispatch: {}

jobs:
  docs:
    name: Build (Hugo)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      HUGO_ENV: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: '0.124.1'
          extended: true

      - name: Build documentation site
        run: hugo --minify --destination public
        working-directory: docs/site

      - name: Upload build artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: docs/site/public
