name: E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        working-directory: frontend
        run: pnpm install --no-frozen-lockfile

      - name: Start application stack
        env:
          POSTGRES_PASSWORD: testpass123
          REDIS_PASSWORD: redispass123
          JWT_SECRET: test_jwt_secret_for_ci_only_not_for_production_use_64_chars_long_extra
          SERVER_ENCRYPTION_KEY: test_encryption_key_32_chars_ok_1234
          CORS_ORIGINS: http://localhost:3000
          VITE_API_URL: http://localhost:8080
        run: |
          docker compose up -d --build --wait
          echo "Services started successfully"

      - name: Run frontend unit tests
        working-directory: frontend
        run: pnpm test

      - name: Install Playwright browsers
        working-directory: frontend
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright e2e tests
        working-directory: frontend
        env:
          BASE_URL: http://localhost:3000
        run: pnpm run test:pw

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== Backend Logs ==="
          docker compose logs backend --tail=100 || true
          echo "=== Frontend Logs ==="
          docker compose logs frontend --tail=100 || true

      - name: Cleanup
        if: always()
        run: docker compose down -v